### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by tytan652**
I'm trying to translate this plugin but I don't see those one in OBS.
```
DWM.Clear="Clear"
DWM.Remove.First="Remove first"
DWM.Remove.Last="Remove last"
DWM.Delete.First="Delete first"
DWM.Delete.Last="Delete last"
```
Also I need to know the context of the use of the word 'watch' in "Directory watch media".
Is it used like in "Watch TV" or more like "Watch the children" ?

### CODE REVIEW

**Comment by exeldro** [comment]
the translation you mention are hotkeys added on a vlc source

watch as checking if something changed

don't mind the failed build check for linux I will fix that

**Comment by tytan652** [comment]
Ok, thanks

**Comment by tytan652** [comment]
What is the difference between "Delete" and "Remove" ?

**Comment by exeldro** [comment]
remove only removes it from the vlc source, delete also deletes the file from disk

**Comment by tytan652** [comment]
I need one more thing, the context of the word 'clear', does it clear VLC source file list ?

**Comment by exeldro** [comment]
yes 'clear' is for clearing the vlc play list

**Comment by tytan652** [comment]
Any with issue with my translation ?

**Pull request merged**
